spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/boostimauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: boostim#auth

webserver:
  url: http://web:8080

socketserver:
  url: http://web-socket:9010